import { OpenAPIHono, createRoute } from '@hono/zod-openapi';
import { ParseRequestSchema, ParseResponseSchema } from '@/schemas';
import { parseSVG } from '@/lib/svg/parser';

const parse = new OpenAPIHono();

const parseRoute = createRoute({
  method: 'post',
  path: '/',
  tags: ['Parse'],
  summary: 'Parse SVG to extract LaTeX',
  description: 'Extract LaTeX equations and metadata from an SVG generated by this API',
  request: {
    body: {
      content: {
        'application/json': {
          schema: ParseRequestSchema,
        },
      },
    },
  },
  responses: {
    200: {
      description: 'Parse result',
      content: {
        'application/json': {
          schema: ParseResponseSchema,
        },
      },
    },
  },
});

parse.openapi(parseRoute, async (c) => {
  const { svg } = c.req.valid('json');

  const result = parseSVG(svg);

  return c.json({
    success: result.errors.length === 0,
    hasMetadata: result.hasMetadata,
    metadata: result.metadata,
    equations: result.equations,
    errors: result.errors,
  });
});

export default parse;
